/*
 * Copyright (c) 2011 Qualcomm Atheros, Inc.
 * All Rights Reserved. 
 * Qualcomm Atheros Confidential and Proprietary. 
 *
 * $ATH_LICENSE_HOSTSDK0_C$
 *
 * This file contains the definitions for wmiconfig utility
 */

#ifndef _WMI_CONFIG_H_
#define _WMI_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

enum {
    WMI_GET_VERSION=501,     /* something that doesn't collide with ascii */
    WMI_SET_POWER_MODE,
    WMI_SET_IBSS_PM_CAPS,
    WMI_SET_PM_PARAMS,
    WMI_SET_SCAN_PARAMS,
    WMI_SET_LISTEN_INTERVAL,
    WMI_SET_BMISS_TIME,
    WMI_SET_BSS_FILTER,
    WMI_SET_RSSI_THRESHOLDS,
    WMI_SET_CHANNEL,
    WMI_SET_SSID,
    WMI_SET_BADAP,
    WMI_DELETE_BADAP,
    WMI_CREATE_QOS,
    WMI_DELETE_QOS,
    WMI_GET_QOS_QUEUE,
    WMI_GET_TARGET_STATS,
    WMI_SET_TARGET_ERROR_REPORTING_BITMASK,
    WMI_SET_AC_PARAMS,
    WMI_SET_ASSOC_IE,
    WMI_SET_DISC_TIMEOUT,
    WMI_SET_ADHOC_BSSID,
    WMI_SET_OPT_MODE,
    WMI_OPT_SEND_FRAME,
    WMI_SET_BEACON_INT,
    WMI_SET_VOICE_PKT_SIZE,
    WMI_SET_MAX_SP,
    WMI_GET_ROAM_TBL,
    WMI_SET_ROAM_CTRL,
    WMI_SET_POWERSAVE_TIMERS,
    WMI_SET_POWERSAVE_TIMERS_PSPOLLTIMEOUT,
    WMI_SET_POWERSAVE_TIMERS_TRIGGERTIMEOUT,
    WMI_GET_POWER_MODE,
    WMI_SET_WLAN_STATE,
    WMI_GET_WLAN_STATE,
    WMI_GET_ROAM_DATA,
    WMI_SET_BT_STATUS,
    WMI_SET_BT_PARAMS,
    WMI_SET_BTCOEX_FE_ANT,
    WMI_SET_BTCOEX_COLOCATED_BT_DEV,
    WMI_SET_BTCOEX_SCO_CONFIG,
    WMI_SET_BTCOEX_A2DP_CONFIG,
    WMI_SET_BTCOEX_ACLCOEX_CONFIG,
    WMI_SET_BTCOEX_BTINQUIRY_PAGE_CONFIG,
    WMI_SET_BTCOEX_DEBUG,
    WMI_SET_BTCOEX_BT_OPERATING_STATUS,
    WMI_GET_BTCOEX_CONFIG,
    WMI_GET_BTCOEX_STATS,
    WMI_SET_RETRYLIMITS,
    WMI_START_SCAN,
    WMI_SET_FIX_RATES,
    WMI_GET_FIX_RATES,
    WMI_SET_SNR_THRESHOLDS,
    WMI_CLR_RSSISNR,
    WMI_SET_LQ_THRESHOLDS,
    WMI_SET_AUTH_MODE,
    WMI_SET_REASSOC_MODE,
    WMI_SET_LPREAMBLE,
    WMI_SET_RTS,
    WMI_SET_WMM,
#ifdef USER_KEYS
    USER_SETKEYS,
#endif
    WMI_APSD_TIM_POLICY,
    WMI_SET_ERROR_DETECTION,
    WMI_GET_HB_CHALLENGE_RESP,
    WMI_SET_TXOP,
    DIAG_ADDR,
    DIAG_DATA,
    DIAG_READ,
    DIAG_WRITE,
    WMI_GET_RD,
    WMI_SET_KEEPALIVE,
    WMI_GET_KEEPALIVE,
    WMI_SET_APPIE,
    WMI_SET_MGMT_FRM_RX_FILTER,
    WMI_DBGLOG_CFG_MODULE,
    WMI_DBGLOG_GET_DEBUG_LOGS,
    WMI_SET_HOST_SLEEP_MODE,
    WMI_SET_WOW_MODE,
    WMI_GET_WOW_LIST,
    WMI_ADD_WOW_PATTERN,
    WMI_DEL_WOW_PATTERN,
    DIAG_DUMP_CHIP_MEM,
    WMI_SET_CONNECT_CTRL_FLAGS,
    DUMP_HTC_CREDITS,
    USER_SETKEYS_INITRSC,
    WMI_SCAN_DFSCH_ACT_TIME,
    WMI_SIMULATED_APSD_TIM_POLICY,
    WMI_SET_AKMP_INFO,
    WMI_AKMP_MULTI_PMKID,
    WMI_NUM_PMKID,
    WMI_PMKID_ENTRY,
    WMI_SET_PMKID_LIST,
    WMI_GET_PMKID_LIST,
    WMI_SET_IEMASK,
    WMI_SCAN_CHANNEL_LIST,
    WMI_SET_BSS_PMKID_INFO,
    WMI_BSS_PMKID_ENTRY,
    WMI_BSSID,
    WMI_ABORT_SCAN,
    WMI_TARGET_EVENT_REPORT,
    WMI_AP_GET_STA_LIST,    /* AP mode */
    WMI_AP_HIDDEN_SSID,     /* AP mode */
    WMI_AP_SET_NUM_STA,     /* AP mode */
    WMI_AP_ACL_POLICY,      /* AP mode */
    WMI_AP_ACL_MAC_LIST1,   /* AP mode */
    WMI_AP_ACL_MAC_LIST2,   /* AP mode */
    WMI_AP_GET_ACL_LIST,    /* AP mode */
    WMI_AP_COMMIT_CONFIG,   /* AP mode */
    WMI_AP_INACT_TIME,      /* AP mode */
    WMI_AP_PROT_TIME,       /* AP mode */    
    WMI_AP_SET_MLME,        /* AP mode */
    WMI_AP_SET_COUNTRY,     /* AP mode */
    WMI_AP_GET_COUNTRY_LIST,/* AP mode */
    WMI_AP_DISABLE_REGULATORY, /* AP mode */
    WMI_AP_SET_DTIM,        /* AP mode */    
    WMI_AP_INTRA_BSS,       /* AP mode */    
    WMI_AP_INTER_BSS,       /* AP mode */    
    WMI_GET_IP,
    WMI_SET_MCAST_FILTER,
    WMI_DEL_MCAST_FILTER,
    WMI_MCAST_FILTER,
    WMI_DUMP_RCV_AGGR_STATS,
    WMI_SETUP_AGGR,
    WMI_CFG_ALLOW_AGGR,
    WMI_CFG_DELE_AGGR,
    WMI_SET_HT_CAP,
    WMI_SET_HT_OP,
    WMI_AP_GET_STAT,        /* AP mode */
    WMI_AP_CLR_STAT,        /* AP mode */
    WMI_SET_TX_SELECT_RATES,
    WMI_SCAN_MAXACT_PER_SSID,
    WMI_AP_GET_HIDDEN_SSID, /* AP mode */
    WMI_AP_GET_COUNTRY,     /* AP mode */
    WMI_AP_GET_WMODE,       /* AP mode */
    WMI_AP_GET_DTIM,        /* AP mode */
    WMI_AP_GET_BINTVL,      /* AP mode */    
    WMI_GET_RTS,
    DIAG_FETCH_TARGET_REGS,
#ifdef ATH_INCLUDE_PAL
    WMI_SEND_PAL_CMD,
    WMI_SEND_PAL_DATA,
#endif
    WMI_SET_WLAN_CONN_PRECDNCE,
    WMI_SET_AP_RATESET,     /* AP mode */
    WMI_SET_TX_WAKEUP_POLICY,
    WMI_SET_TX_NUM_FRAMES_TO_WAKEUP,
    WMI_SET_AP_PS,
    WMI_SET_AP_PS_PSTYPE,
    WMI_SET_AP_PS_IDLE_TIME,
    WMI_SET_AP_PS_PS_PERIOD,
    WMI_SET_AP_PS_SLEEP_PERIOD,
    WMI_SEND_CONNECT_CMD,
    WMI_SEND_CONNECT_CMD1,
    WMI_SEND_CONNECT_CMD2,
    WMI_SET_WOW_FILTER,
    WMI_SET_WOW_HOST_REQ_DELAY,
    WMI_SET_QOS_SUPP,
    WMI_SET_AC_VAL,
    BT_HW_POWER_STATE,
    SET_BT_HW_POWER_STATE,
    GET_BT_HW_POWER_STATE,
    DIAG_DUMP_CHIP_MEM_VENUS,
    WMI_SET_TX_SGI_PARAM,
    WMI_SGI_MASK,
    WMI_PER_SGI,
    WMI_WAC_ENABLE,
    WMI_SET_WPA_OFFLOAD_STATE,
    WMI_SET_DIVERSITY_PARAM,
    WMI_ENABLE_PKTLOG,
    WMI_PKTLOG_EVLIST,
    WMI_PKTLOG_TCPHDR,
    WMI_PKTLOG_TRIGGER,
    WMI_PKTLOG_TRIGGER_THRESH,
    WMI_PKTLOG_TRIGGER_INT,
    WMI_PKTLOG_TAIL_COUNT,
    WMI_PKTLOG_BUF_SIZE,
    WMI_DISABLE_PKTLOG,
    WMI_GET_PKTLOG,
    WMI_AP_ACS_DISABLE_HI_CHANNELS,
    WMI_SET_EXCESS_TX_RETRY_THRES,
    WMI_AP_SET_APSD,
    WMI_AP_SET_GNUM_STA,
    WMI_AP_GET_GNUM_STA,
    WMI_AP_GET_NUM_STA,
    WMI_GET_HT_CAP,
    WMI_SCAN_PROBED_SSID,
    WMI_FORCE_ASSERT,
    WMI_ADD_WOW_EXT_PATTERN,
    WMI_SET_ARP_NS_OFFLOAD,
    WMI_GET_GTK_STATUS,    
    DIAG_DUMP_CHIP_MEM_MCK,
    WMI_DISABLE_11B_RATES,
    WMI_REMAIN_ON_CHNL,
    WMI_CANCEL_REMAIN_ON_CHNL,
    WMI_SEND_ACTION,
    WMI_PROBE_REPORT_REQ,
    WMI_SEND_PROBE_RESPONSE,
    WMI_P2P_GET_INFO_REQ,	
    WMI_SMPS_CONFIG,
    WMI_SMPS_SMPSMODE,
    WMI_SMPS_AUTO,
    WMI_SMPS_DATATHRESH,
    WMI_SMPS_RSSITHRESH,
    WMI_SMPS_ENABLE,
    WMI_SET_RATECTRL_PARM,
    WMI_SET_BUNDLE_PARAM,
    WMI_SET_USB_SUSPEND,
    WMI_SET_HTCAP_ALLZERO,
    WMI_SET_UAPSD_ON,
    WMI_SET_UAPSD_OFF,
    WMI_SET_AP_KEEPALIVE_OFF,
};

//#define SIOCGADFWIOCTL  _IOWR('i', 237, ioctl_wcmd_t)
#define AR6000_IOCTL_EXTENDED		(SIOCDEVPRIVATE+15)

typedef enum {
    AR6000_XIOCTL_BMI_DONE = 1,
    AR6000_XIOCTL_BMI_READ_MEMORY,
    AR6000_XIOCTL_BMI_WRITE_MEMORY,
    AR6000_XIOCTL_BMI_EXECUTE,
    AR6000_XIOCTL_BMI_SET_APP_START,
    AR6000_XIOCTL_BMI_READ_SOC_REGISTER,
    AR6000_XIOCTL_BMI_WRITE_SOC_REGISTER,
    AR6000_XIOCTL_BMI_TEST,
    AR6000_XIOCTL_UNUSED9,
    AR6000_XIOCTL_UNUSED10,
    AR6000_XIOCTL_UNUSED11,
    AR6000_XIOCTL_FORCE_TARGET_RESET,
    AR6000_XIOCTL_HTC_RAW_OPEN,
    AR6000_XIOCTL_HTC_RAW_CLOSE,
    AR6000_XIOCTL_HTC_RAW_READ,
    AR6000_XIOCTL_HTC_RAW_WRITE,
    AR6000_XIOCTL_CHECK_TARGET_READY,
    AR6000_XIOCTL_GPIO_OUTPUT_SET,
    AR6000_XIOCTL_GPIO_INPUT_GET,
    AR6000_XIOCTL_GPIO_REGISTER_SET,
    AR6000_XIOCTL_GPIO_REGISTER_GET,
    AR6000_XIOCTL_GPIO_INTR_ACK,
    AR6000_XIOCTL_GPIO_INTR_WAIT,
    AR6000_XIOCTL_SET_ADHOC_BSSID,
    AR6000_XIOCTL_SET_OPT_MODE,
    AR6000_XIOCTL_OPT_SEND_FRAME,
    AR6000_XIOCTL_SET_BEACON_INTVAL,
    IEEE80211_IOCTL_SETAUTHALG,
    AR6000_XIOCTL_SET_VOICE_PKT_SIZE,
    AR6000_XIOCTL_SET_MAX_SP,
    AR6000_XIOCTL_WMI_GET_ROAM_TBL,
    AR6000_XIOCTL_WMI_SET_ROAM_CTRL,
    AR6000_XIOCTRL_WMI_SET_POWERSAVE_TIMERS,
    AR6000_XIOCTRL_WMI_GET_POWER_MODE,
    AR6000_XIOCTRL_WMI_SET_WLAN_STATE,
    AR6000_XIOCTL_WMI_GET_ROAM_DATA,
    AR6000_XIOCTL_WMI_SETRETRYLIMITS,
    AR6000_XIOCTL_TCMD_CONT_TX,
    AR6000_XIOCTL_TCMD_CONT_RX,
    AR6000_XIOCTL_TCMD_PM,
    AR6000_XIOCTL_WMI_STARTSCAN,
    AR6000_XIOCTL_WMI_SETFIXRATES,
    AR6000_XIOCTL_WMI_GETFIXRATES,
    AR6000_XIOCTL_WMI_SET_RSSITHRESHOLD,
    AR6000_XIOCTL_WMI_CLR_RSSISNR,                   
    AR6000_XIOCTL_WMI_SET_LQTHRESHOLD,               
    AR6000_XIOCTL_WMI_SET_RTS,
    AR6000_XIOCTL_WMI_SET_LPREAMBLE,
    AR6000_XIOCTL_WMI_SET_AUTHMODE,
    AR6000_XIOCTL_WMI_SET_REASSOCMODE,
    AR6000_XIOCTL_WMI_SET_WMM,
    AR6000_XIOCTL_WMI_SET_HB_CHALLENGE_RESP_PARAMS,
    AR6000_XIOCTL_WMI_GET_HB_CHALLENGE_RESP,
    AR6000_XIOCTL_WMI_GET_RD,
    AR6000_XIOCTL_DIAG_READ,
    AR6000_XIOCTL_DIAG_WRITE,
    AR6000_XIOCTL_WMI_SET_TXOP,
    AR6000_XIOCTL_USER_SETKEYS,
    AR6000_XIOCTL_WMI_SET_KEEPALIVE,
    AR6000_XIOCTL_WMI_GET_KEEPALIVE,
    AR6000_XIOCTL_BMI_ROMPATCH_INSTALL,
    AR6000_XIOCTL_BMI_ROMPATCH_UNINSTALL,
    AR6000_XIOCTL_BMI_ROMPATCH_ACTIVATE,
    AR6000_XIOCTL_BMI_ROMPATCH_DEACTIVATE,
    AR6000_XIOCTL_WMI_SET_APPIE,
    AR6000_XIOCTL_WMI_SET_MGMT_FRM_RX_FILTER,
    AR6000_XIOCTL_DBGLOG_CFG_MODULE,
    AR6000_XIOCTL_DBGLOG_GET_DEBUG_LOGS,
    AR6000_XIOCTL_WMI_SET_WSC_STATUS = 70,
    AR6000_XIOCTL_WMI_SET_BT_STATUS,
    AR6000_XIOCTL_WMI_SET_BT_PARAMS,
    AR6000_XIOCTL_WMI_SET_HOST_SLEEP_MODE,
    AR6000_XIOCTL_WMI_SET_WOW_MODE,
    AR6000_XIOCTL_WMI_GET_WOW_LIST,
    AR6000_XIOCTL_WMI_ADD_WOW_PATTERN,
    AR6000_XIOCTL_WMI_DEL_WOW_PATTERN,
    AR6000_XIOCTL_TARGET_INFO,
    AR6000_XIOCTL_DUMP_HTC_CREDIT_STATE,
    AR6000_XIOCTL_TRAFFIC_ACTIVITY_CHANGE,
    AR6000_XIOCTL_WMI_SET_CONNECT_CTRL_FLAGS,
    AR6000_XIOCTL_WMI_SET_AKMP_PARAMS,
    AR6000_XIOCTL_WMI_GET_PMKID_LIST,
    AR6000_XIOCTL_WMI_SET_PMKID_LIST,
    AR6000_XIOCTL_WMI_SET_PARAMS,
    AR6000_XIOCTL_WMI_SET_MCAST_FILTER,
    AR6000_XIOCTL_WMI_DEL_MCAST_FILTER,
    AR6000_XIOCTL_UNUSED90 = 90,
    AR6000_XIOCTL_BMI_LZ_STREAM_START,
    AR6000_XIOCTL_BMI_LZ_DATA,
    AR6000_XIOCTL_PROF_CFG,
    AR6000_XIOCTL_PROF_ADDR_SET,
    AR6000_XIOCTL_PROF_START,
    AR6000_XIOCTL_PROF_STOP,
    AR6000_XIOCTL_PROF_COUNT_GET,
    AR6000_XIOCTL_WMI_ABORT_SCAN,
    AR6000_XIOCTL_AP_GET_STA_LIST,
    AR6000_XIOCTL_AP_HIDDEN_SSID,
    AR6000_XIOCTL_AP_SET_NUM_STA,
    AR6000_XIOCTL_AP_SET_ACL_MAC,
    AR6000_XIOCTL_AP_GET_ACL_LIST,
    AR6000_XIOCTL_AP_COMMIT_CONFIG,
    IEEE80211_IOCTL_GETWPAIE,
    AR6000_XIOCTL_AP_CONN_INACT_TIME,
    AR6000_XIOCTL_AP_PROT_SCAN_TIME,
    AR6000_XIOCTL_AP_SET_COUNTRY,
    AR6000_XIOCTL_AP_SET_DTIM,
    AR6000_XIOCTL_WMI_TARGET_EVENT_REPORT,
    AR6000_XIOCTL_SET_IP,
    AR6000_XIOCTL_AP_SET_ACL_POLICY,
    AR6000_XIOCTL_AP_CTRL_BSS_COMM,
    AR6000_XIOCTL_DUMP_MODULE_DEBUG_INFO,
    AR6000_XIOCTL_MODULE_DEBUG_SET_MASK,
    AR6000_XIOCTL_MODULE_DEBUG_GET_MASK,
    AR6000_XIOCTL_DUMP_RCV_AGGR_STATS,
    AR6000_XIOCTL_SET_HT_CAP,
    AR6000_XIOCTL_SET_HT_OP,
    AR6000_XIOCTL_AP_GET_STAT,
    AR6000_XIOCTL_SET_TX_SELECT_RATES,
    AR6000_XIOCTL_SETUP_AGGR,
    AR6000_XIOCTL_ALLOW_AGGR,
    AR6000_XIOCTL_AP_GET_HIDDEN_SSID,
    AR6000_XIOCTL_AP_GET_COUNTRY,
    AR6000_XIOCTL_AP_GET_WMODE,
    AR6000_XIOCTL_AP_GET_DTIM,
    AR6000_XIOCTL_AP_GET_BINTVL,
    AR6000_XIOCTL_AP_GET_RTS,
    AR6000_XIOCTL_DELE_AGGR,
    AR6000_XIOCTL_FETCH_TARGET_REGS,
    AR6000_XIOCTL_HCI_CMD,
    AR6000_XIOCTL_ACL_DATA,
    AR6000_XIOCTL_WLAN_CONN_PRECEDENCE,
    AR6000_XIOCTL_AP_SET_11BG_RATESET,
    AR6000_XIOCTL_WMI_SET_AP_PS,
    AR6000_XIOCTL_WMI_MCAST_FILTER,
    AR6000_XIOCTL_WMI_SET_BTCOEX_FE_ANT,
    AR6000_XIOCTL_WMI_SET_BTCOEX_COLOCATED_BT_DEV,
    AR6000_XIOCTL_WMI_SET_BTCOEX_BTINQUIRY_PAGE_CONFIG,
    AR6000_XIOCTL_WMI_SET_BTCOEX_SCO_CONFIG,
    AR6000_XIOCTL_WMI_SET_BTCOEX_A2DP_CONFIG,
    AR6000_XIOCTL_WMI_SET_BTCOEX_ACLCOEX_CONFIG,
    AR6000_XIOCTL_WMI_SET_BTCOEX_DEBUG,
    AR6000_XIOCTL_WMI_SET_BT_OPERATING_STATUS,
    AR6000_XIOCTL_WMI_GET_BTCOEX_CONFIG,
    AR6000_XIOCTL_WMI_GET_BTCOEX_STATS,
    AR6000_XIOCTL_WMI_SET_QOS_SUPP,
    AR6000_XIOCTL_WMI_P2P_DISCOVER,
    AR6000_XIOCTL_WMI_P2P_STOP_FIND,
    AR6000_XIOCTL_WMI_P2P_CANCEL,
    AR6000_XIOCTL_WMI_P2P_LISTEN,
    AR6000_XIOCTL_WMI_P2P_GO_NEG,
    AR6000_XIOCTL_WMI_P2P_AUTH_GO_NEG,
    AR6000_XIOCTL_WMI_P2P_REJECT,
    AR6000_XIOCTL_WMI_P2P_CONFIG,
    AR6000_XIOCTL_WMI_WPS_CONFIG,
    AR6000_XIOCTL_WMI_P2P_FINDNODE,
    AR6000_XIOCTL_WMI_P2P_GRP_INIT,
    AR6000_XIOCTL_WMI_P2P_GRP_FORMATION_DONE,
    AR6000_XIOCTL_WMI_P2P_INVITE,
    AR6000_XIOCTL_WMI_P2P_PROV_DISC,
    AR6000_XIOCTL_WMI_P2P_SET,
    AR6000_XIOCTL_WMI_P2P_PEER,
    AR6000_XIOCTL_WMI_P2P_FLUSH,
    AR6000_XIOCTL_WMI_GET_GO_PARAMS,
    AR6000_XIOCTL_WMI_P2P_AUTH_INVITE,
    AR6000_XIOCTL_WMI_P2P_GET_IF_ADDR,
    AR6000_XIOCTL_WMI_P2P_GET_DEV_ADDR,
    AR6000_XIOCTL_WMI_P2P_SDPD_TX_CMD,
    AR6000_XIOTCL_WMI_P2P_SD_CANCEL_REQUEST,
    AR6000_XIOCTL_SET_BT_HW_POWER_STATE,
    AR6000_XIOCTL_GET_BT_HW_POWER_STATE,
    AR6000_XIOCTL_GET_WLAN_SLEEP_STATE,
    AR6000_XIOCTL_WMI_SET_TX_SGI_PARAM,
    AR6000_XIOCTL_WMI_ENABLE_WAC_PARAM,
    AR6000_XIOCTL_WAC_SCAN_REPLY,
    AR6000_XIOCTL_WMI_WAC_CTRL_REQ,
    AR6000_XIOCTL_WMI_SET_WPA_OFFLOAD_STATE,
    AR6000_XIOCTL_WMI_SET_PASSPHRASE,
    AR6000_XIOCTL_BMI_NVRAM_PROCESS,
    AR6000_XIOCTL_WMI_SET_DIVERSITY_PARAM,
    AR6000_XIOCTL_WMI_ENABLE_PKTLOG,
    AR6000_XIOCTL_WMI_DISABLE_PKTLOG,
    AR6000_XIOCTL_WMI_GET_PKTLOG,
    AR6000_XIOCTL_TCMD_CMDS,
    AR6000_XIOCTL_AP_ACS_DISABLE_HI_CHANNELS,
    AR6000_XIOCTL_WMI_SET_EXCESS_TX_RETRY_THRES, 
    AR6000_XIOCTL_WMI_AP_SET_APSD,
    AR6000_XIOCTL_AP_GET_NUM_STA,
    AR6000_XIOCTL_GET_HT_CAP,
    AR6000_XIOCTL_GET_SUBMODE,
    AR6000_XIOCTL_WMI_GET_P2P_IE,
    AR6000_XIOCTL_TCMD_SETREG,
    AR6000_XIOCTL_WMI_FORCE_ASSERT,
    AR6000_XIOCTL_WMI_ADD_WOW_EXT_PATTERN,
    AR6000_XIOCTL_WMI_SET_ARP_NS_OFFLOAD,
    AR6000_XIOCTL_WMI_SET_GTK_OFFLOAD,
    AR6000_XIOCTL_WMI_GET_GTK_STATUS,
    AR6000_XIOCTL_DISABLE_11B_RATES,
    AR6000_XIOCTL_REMAIN_ON_CHNL,
    AR6000_XIOCTL_CANCEL_REMAIN_ON_CHNL,
    AR6000_XIOCTL_SEND_ACTION,
    AR6000_XIOCTL_PROBE_REPORT_REQ,
    AR6000_XIOCTL_SEND_PROBE_RESPONSE,
    AR6000_XIOCTL_P2P_GET_INFO_REQ,	
    AR6000_XIOCTL_WMI_P2P_GET_OWN_INFO,
    AR6000_XIOCTL_WMI_ENABLE_SMPS,
    AR6000_XIOCTL_WMI_CONFIG_SMPS,
    AR6000_XIOCTL_WMI_RATECTRL,
    AR6000_XIOCTL_WMI_SET_BUNDLE_PARAM,
    AR6000_XIOCTL_WMI_SET_USB_SUSPEND,
    AR6000_XIOCTL_WMI_SET_HT_CAP_ALL_ZERO,
    AR6000_XIOCTL_WMI_SET_UAPSD_ON,
    AR6000_XIOCTL_WMI_SET_UAPSD_OFF,
    AR6000_XIOCTL_WMI_SET_AP_KEEPALIVE_OFF,
} XTND_IOCLTS; 
#if 0
/*
***************************************************************************
**  How to form a regcode from CountryCode, Regulatory domain or WWR code:
**
**  WWR code is nothing but a special case of Regulatory domain.
**
**      code is of type U_INT32
**
**      Bit-31  Bit-30      Bit11-0
**        0       0          xxxx    -> Bit11-0 is a Regulatory Domain
**        0       1          xxxx    -> Bit11-0 is a WWR code
**        1       X          xxxx    -> Bit11-0 is a Country code
**  
***************************************************************************
*/
#define REGCODE_IS_CC_BITSET(x)     ((x) & 0x80000000)
#define REGCODE_GET_CODE(x)         ((x) & 0xFFF)
#define REGCODE_IS_WWR_BITSET(x)    ((x) & 0x40000000)
#ifdef ATH_INCLUDE_PAL
#define MAX_BUFFER_SIZE             1512    
#endif

typedef struct {
    A_UINT32        numPMKIDUser;          /* PMKIDs user wants to enter */
    WMI_SET_PMKID_LIST_CMD  *pmkidInfo;
} pmkidUserInfo_t;

#define KEYTYPE_PSK     1
#define KEYTYPE_PHRASE  2

typedef struct {
    char ssid[WMI_MAX_SSID_LEN];
    A_UINT8 ssid_len;
    A_UINT8 wpa;
    A_UINT8 ucipher;
    A_UINT8 mcipher;
    char    psk[64];
    A_UINT8 psk_type;
    A_UINT8 pmk[WMI_PMK_LEN];
    A_UINT8 auth;
    A_UINT8 wep_key[4][26];
    A_UINT8 def_wep_key;
} profile_t;
#endif

#ifdef __cplusplus
}
#endif

#endif /* _WMI_CONFIG_H_ */
